name: Docker Build and Push

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup dotnet v8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Install dependencies
        run: dotnet restore ./BoardGameTracker.Tests/BoardGameTracker.Tests.csproj
      - name: Test with dotnet
        run: dotnet test ./BoardGameTracker.Tests/BoardGameTracker.Tests.csproj --no-restore --logger trx --results-directory "TestResults" --collect "XPlat Code Coverage" --settings CodeCoverage.runsettings
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: backend-tests
          path: TestResults
        if: ${{ always() }}

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  build-docker:
    needs: build
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.3.0
        id: versioning
        with:
          enable_prerelease_mode: ${{ github.ref == 'refs/heads/dev' }}
          namespace: ${{ github.ref == 'refs/heads/dev' && 'beta' || '' }}
          bump_each_commit: true
          version_format: "${major}.${minor}.${patch}-pre${increment}"
          debug: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: Dockerfile
          tags: |
            uping/boardgametracker:${{ github.ref == 'refs/heads/master' && 'latest' || 'dev' }}
          build-args: |
            VERSION=${{ steps.versioning.outputs.version }}
