name: Docker Build and Push

on:
  push:
    branches:
      - dev
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.3.0
        id: versioning
        with:
          enable_prerelease_mode: ${{ github.ref == 'refs/heads/dev' }}
          namespace: ${{ github.ref == 'refs/heads/dev' && 'beta' || '' }}
          bump_each_commit: true
          bump_each_commit_patch_pattern: "*bump version*"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: Dockerfile
          tags: |
            uping/boardgametracker:${{ github.ref == 'refs/heads/master' && 'latest' || 'dev' }}
          build-args: |
            VERSION=${{ steps.versioning.outputs.version }}
